### ISSUE TITLE
[Documentation] Framework Wiki: Main Ticket

### ISSUE THREAD

**Issue by dgibso29** [Bubbus/F3_CA_BUB#7]
This is a big one and a placeholder for what will need to be done to make this framework accessible to other missionmakers.

**Todo:**
- [ ]  update the classic "YOU'RE NOT DONE YET" wiki for CA2, put it on the repo's wiki page
- [ ]  make some standard compositions available on workshop, link and explain them on the wiki
- [ ]  make a "how 2 basic zeus mission" page, reuse some of the YNDY links in it but cover gaps with advice tailored to this

**Comment by dgibso29** [comment]
Closing as scope and tasks are outdated.
